### ISSUE TITLE
ALL - Color Scheme

### ISSUE THREAD

**Issue by 7h1nk3r** [DanielCanonEllis/16S-GUI-DB#26]
- [ ] Decide on a color scheme

**Comment by blaisegraham** [comment]
What do you guys think of this as the color scheme? I can tone it down if it's too bright

![screen shot 2016-03-23 at 4 00 38 pm](https://cloud.githubusercontent.com/assets/8551384/14000741/8c6a8482-f110-11e5-8696-db6522d9d1d1.png)

**Comment by blaisegraham** [comment]
Jk i like this one

![screen shot 2016-03-23 at 5 05 21 pm](https://cloud.githubusercontent.com/assets/8551384/14002354/740ab62e-f119-11e5-95f2-32ba9430e7a5.png)

**Comment by blaisegraham** [comment]
@DanielCanonEllis
